function [ fitting_results ] = to_calculate_errors_parameters_using_Boostrapping...
    ( input,models,fitting_results,original_best_model,timing_phase,blastomere,nbEmbryo_givenCondition,...
    tmin,fixed_short_lifetime,fixed_short_percent,save_stem,plot_visualization )

% to implement the computation of error through performing boostraping with replacement
% see courses from Loyed-Smith and "cours_mle_introduction"

% for each dataset generated by boostrapping, we perform the fit and get a
% set of parameters. This is repeat N times the size of the initial data
% set. The errors of the parameters are estimated from the standadr
% deviation
% on the optimized parameters.

if ~exist('plot_visualization','var')
    plot_visualization = 0;
end

global param


%% get mean size of sample to estimnate number of boostrap for later

size_population_raw = 0;

for iEmbryo = 1 : nbEmbryo_givenCondition
    
    name_embryo = ['embryo' num2str(iEmbryo)];
    size_population_raw =  size_population_raw + nansum( input.(name_embryo).data(:,2) );
    size_population.(name_embryo).raw = nansum( input.(name_embryo).data(:,2) );
    
end

size_population.total.raw = size_population_raw;
fitting_results.size_population = size_population;
size_population_mean = size_population_raw /nbEmbryo_givenCondition;


%% define and allocates variables

match_model = 0;

if strcmp(original_best_model,'MonoExpo')
    sample_tau = [];
elseif strcmp(original_best_model,'DoubleExpo')
    sample_tau1 = [];
    sample_tau2 = [];
    sample_prop = [];
elseif strcmp(original_best_model,'TripleExpo')
    sample_tau1_ = [];
    sample_tau2_ = [];
    sample_tau3_ = [];
    sample_prop1_ = [];
    sample_prop2_ = [];
elseif strcmp(original_best_model,'QuadroExpo')
    sample_tau4_1 = [];
    sample_tau4_2 = [];
    sample_tau4_3 = [];
    sample_tau4_4 = [];
    sample_prop4_1 = [];
    sample_prop4_2 = [];
    sample_prop4_3 = [];
end


%% generate new data and fit their duration distribution to get a sample of model parameters

if size_population_mean < 4000
    loop_nb = size_population_mean;
elseif size_population_mean >= 4000
    loop_nb = 4000;
% else
%     loop_nb = size_population_mean;
end
fitting_results.bootstrap_number = loop_nb;

for iSample = 1 : loop_nb
    
    for iEmbryo = 1 : nbEmbryo_givenCondition
        
        extension = ['embryo' num2str(iEmbryo)];
        
        tmax = max(input.(extension).raw_data)./param.sp6;
        
        new_binranges = [tmin : 0.1 : tmax].*param.sp6;
        new_sample = datasample( input.(extension).raw_data,length(input.(extension).raw_data) );
        [new_bincounts] = hist(new_sample, new_binranges);
        
        nb_zero = 0;
        index_zero = [];
        for i = 1 : length(new_bincounts)
            if new_bincounts(i) ==0
                nb_zero = nb_zero+1;
                index_zero = [[index_zero] i ];
            end
            if nb_zero == 10
                max_index = i;
                break
            end
        end
        if nb_zero < 10
            max_index = max(index_zero);
        end
        max_max_index = length(new_bincounts);
        index_to_remove2 = [(max_index):(max_max_index)];
        new_binranges(index_to_remove2) = [];
        new_bincounts(index_to_remove2) = [];
        
        nb_one = 0;
        index_one = [];
        for i = 1 : length(new_bincounts)
            if new_bincounts(i) ==1
                nb_one = nb_one+1;
                index_one = [[index_one] i ];
            end
            if nb_one == 3
                max_index_one = i;
                break
            end
        end
        if nb_one < 3
            max_index_one = max(index_one);
        end
        max_max_index_one = length(new_bincounts);
        bincounts_above_max_one = 0;
        for index = max_index_one+1 : max_max_index_one
            bincounts_above_max_one = bincounts_above_max_one + new_bincounts(index);
        end
        if max_max_index_one >= (max_index_one + 1)
            bincounts_above_max_one = bincounts_above_max_one / (max_max_index_one - max_index_one - 1);
            
            if ~isnan(bincounts_above_max_one)
                index_to_remove3 = [(max_index_one):(max_max_index_one)];
                new_binranges(index_to_remove3) = [];
                new_bincounts(index_to_remove3) = [];
                new_binranges(max_index_one) = max_index_one + ( max_max_index_one - max_index_one)/2;
                new_bincounts(max_index_one) = bincounts_above_max_one;
            end
        end
        
        % check for any inf in data
        [ ri] = find(~isfinite(new_bincounts));
        new_bincounts(ri)= [];
        new_binranges(ri)= [];
        index_to_remove_inf = find(isinf(new_bincounts));
        new_binranges(index_to_remove_inf) = [];
        new_bincounts(index_to_remove_inf) = [];
        
        new_data = [new_binranges(:)./param.sp6 new_bincounts(:)];
        new_binranges = new_binranges ./ param.sp6;
        new_input.(extension).data = double( new_data );
        
    end
    
    [ new_input,new_fitting_results] = to_calculate_parameters_using_fmincon_sum_mle...
        ( new_input,models,nbEmbryo_givenCondition,1,fixed_short_lifetime,fixed_short_percent );
    
    [ model_choice,best_model ] = to_find_best_model_sum_mle( new_input,new_fitting_results,nbEmbryo_givenCondition,models );
    if strcmp(original_best_model,best_model)
        match_model = match_model +1;
    end
    % to_plot_data_withBestFit_sum_mle_noError( new_input,new_fitting_results,best_model,nbEmbryo_givenCondition,'','',save_stem,2 );
    
    if strcmp(original_best_model,'MonoExpo')
        sample_tau = [ [sample_tau] new_fitting_results.MonoExpo.T];
    elseif strcmp(original_best_model,'DoubleExpo')
        sample_tau1 = [ [sample_tau1] new_fitting_results.DoubleExpo.T1];
        sample_tau2 = [ [sample_tau2] new_fitting_results.DoubleExpo.T2];
        sample_prop = [ [sample_prop] new_fitting_results.DoubleExpo.P1];
    elseif strcmp(original_best_model,'TripleExpo')
        sample_tau1_ = [ [sample_tau1_] new_fitting_results.TripleExpo.TT1];
        sample_tau2_ = [ [sample_tau2_] new_fitting_results.TripleExpo.TT2];
        sample_tau3_ = [ [sample_tau3_] new_fitting_results.TripleExpo.TT3];
        sample_prop1_ = [ [sample_prop1_] new_fitting_results.TripleExpo.PP1];
        sample_prop2_ = [ [sample_prop2_] new_fitting_results.TripleExpo.PP2];
    elseif strcmp(original_best_model,'QuadroExpo')
        sample_tau4_1 = [ [sample_tau4_1] new_fitting_results.QuadroExpo.TTT1];
        sample_tau4_2 = [ [sample_tau4_2] new_fitting_results.QuadroExpo.TTT2];
        sample_tau4_3 = [ [sample_tau4_3] new_fitting_results.QuadroExpo.TTT3];
        sample_tau4_4 = [ [sample_tau4_4] new_fitting_results.QuadroExpo.TTT4];
        sample_prop4_1 = [ [sample_prop4_1] new_fitting_results.QuadroExpo.PPP1];
        sample_prop4_2 = [ [sample_prop4_2] new_fitting_results.QuadroExpo.PPP2];
        sample_prop4_3 = [ [sample_prop4_3] new_fitting_results.QuadroExpo.PPP3];
    end
    
    clear new_input new_fitting_results best_model model_choice
end


%% save results in fitting_results structure

fitting_results.match_model = match_model;
if strcmp(original_best_model,'MonoExpo')
    fitting_results.MonoExpo.T_se_bootstrap = std(sample_tau);
    fitting_results.MonoExpo.T_mean_bootstrap = mean(sample_tau);
    fitting_results.MonoExpo.T_CI_bootstrap = prctile(sample_tau,[2.5 97.5]);
    
elseif strcmp(original_best_model,'DoubleExpo')
    fitting_results.DoubleExpo.T1_se_bootstrap = std(sample_tau1);
    fitting_results.DoubleExpo.T2_se_bootstrap = std(sample_tau2);
    fitting_results.DoubleExpo.P1_se_bootstrap = std(sample_prop);
    fitting_results.DoubleExpo.P2_se_bootstrap = std(sample_prop);
    
    fitting_results.DoubleExpo.T1_mean_bootstrap = mean(sample_tau1);
    fitting_results.DoubleExpo.T2_mean_bootstrap = mean(sample_tau2);
    fitting_results.DoubleExpo.P1_mean_bootstrap = mean(sample_prop);
    fitting_results.DoubleExpo.P2_mean_bootstrap = 1-mean(sample_prop);
    
    fitting_results.DoubleExpo.T1_CI_bootstrap = prctile(sample_tau1,[2.5 97.5]);
    fitting_results.DoubleExpo.T2_CI_bootstrap = prctile(sample_tau2,[2.5 97.5]);
    fitting_results.DoubleExpo.P1_CI_bootstrap = prctile(sample_prop,[2.5 97.5]);
    
elseif strcmp(original_best_model,'TripleExpo')
    fitting_results.TripleExpo.TT1_se_bootstrap = std(sample_tau1_);
    fitting_results.TripleExpo.TT2_se_bootstrap = std(sample_tau2_);
    fitting_results.TripleExpo.TT3_se_bootstrap = std(sample_tau3_);
    fitting_results.TripleExpo.PP1_se_bootstrap = std(sample_prop1_);
    fitting_results.TripleExpo.PP2_se_bootstrap = std(sample_prop2_);
    fitting_results.TripleExpo.PP3_se_bootstrap = std(sample_prop2_);
    
    fitting_results.TripleExpo.TT1_mean_bootstrap = mean(sample_tau1_);
    fitting_results.TripleExpo.TT2_mean_bootstrap = mean(sample_tau2_);
    fitting_results.TripleExpo.TT3_mean_bootstrap = mean(sample_tau3_);
    fitting_results.TripleExpo.PP1_mean_bootstrap = mean(sample_prop1_);
    fitting_results.TripleExpo.PP2_mean_bootstrap = mean(sample_prop2_);
    fitting_results.TripleExpo.PP3_mean_bootstrap = 1 - mean(sample_prop1_) - mean(sample_prop2_);    
    
    fitting_results.TripleExpo.TT1_CI_bootstrap = prctile(sample_tau1_,[2.5 97.5]);
    fitting_results.TripleExpo.TT2_CI_bootstrap = prctile(sample_tau2_,[2.5 97.5]);
    fitting_results.TripleExpo.TT3_CI_bootstrap = prctile(sample_tau3_,[2.5 97.5]);
    fitting_results.TripleExpo.PP1_CI_bootstrap = prctile(sample_prop1_,[2.5 97.5]);
    fitting_results.TripleExpo.PP2_CI_bootstrap = prctile(sample_prop2_,[2.5 97.5]);   
    
elseif strcmp(original_best_model,'QuadroExpo')
    fitting_results.QuadroExpo.TTT1_se_bootstrap = std(sample_tau4_1);
    fitting_results.QuadroExpo.TTT2_se_bootstrap = std(sample_tau4_2);
    fitting_results.QuadroExpo.TTT3_se_bootstrap = std(sample_tau4_3);
    fitting_results.QuadroExpo.TTT4_se_bootstrap = std(sample_tau4_4);
    fitting_results.QuadroExpo.PPP1_se_bootstrap = std(sample_prop4_1);
    fitting_results.QuadroExpo.PPP2_se_bootstrap = std(sample_prop4_2);
    fitting_results.QuadroExpo.PPP3_se_bootstrap = std(sample_prop4_3);
    fitting_results.QuadroExpo.PPP4_se_bootstrap = std(sample_prop4_3);
    
    fitting_results.QuadroExpo.TTT1_mean_bootstrap = mean(sample_tau4_1);
    fitting_results.QuadroExpo.TTT2_mean_bootstrap = mean(sample_tau4_2);
    fitting_results.QuadroExpo.TTT3_mean_bootstrap = mean(sample_tau4_3);
    fitting_results.QuadroExpo.TTT4_mean_bootstrap = mean(sample_tau4_4);
    fitting_results.QuadroExpo.PPP1_mean_bootstrap = mean(sample_prop4_1);
    fitting_results.QuadroExpo.PPP2_mean_bootstrap = mean(sample_prop4_2);
    fitting_results.QuadroExpo.PPP3_mean_bootstrap = mean(sample_prop4_3);
    
end

%% to visualize the results of boostrapping

if plot_visualization == 1
    if strcmp(original_best_model,'MonoExpo')
        
        figure
        hist(sample_tau, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T: ', num2str(round2(mean(sample_tau),2e-2)), ' \pm ',  num2str(round2(std(sample_tau),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_T-MonoExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
    elseif strcmp(original_best_model,'DoubleExpo')
        
        figure
        hist(sample_tau1, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T1: ', num2str(round2(mean(sample_tau1),2e-2)), ' \pm ',  num2str(round2(std(sample_tau1),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_T1-DoubleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_tau2, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T2: ', num2str(round2(mean(sample_tau2),2e-2)), ' \pm ',  num2str(round2(std(sample_tau2),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_T2-DoubleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_prop, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'P1: ', num2str(round2(mean(sample_prop.*100),2e-1)), ' \pm ',  num2str(round2(std(sample_prop.*100),2e-1)) ,' %'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_P1-DoubleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
    elseif strcmp(original_best_model,'TripleExpo')
        
        figure
        hist(sample_tau1_, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T1: ', num2str(round2(mean(sample_tau1_),2e-2)), ' \pm ',  num2str(round2(std(sample_tau1_),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_TT1-TripleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_tau2_, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T2: ', num2str(round2(mean(sample_tau2_),2e-2)), ' \pm ',  num2str(round2(std(sample_tau2_),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_TT2-TripleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_tau3_, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'T3: ', num2str(round2(mean(sample_tau3_),2e-2)), ' \pm ',  num2str(round2(std(sample_tau3_),2e-2)) ,' s'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_TT3-TripleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_prop1_, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'P1: ', num2str(round2(mean(sample_prop1_.*100),2e-1)), ' \pm ',  num2str(round2(std(sample_prop1_.*100),2e-1)) ,' %'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_PP1_TripleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
        figure
        hist(sample_prop2_, 20);
        xlabel('Duration (s)','FontSize',10);
        ylabel('Counts','FontSize',10);
        string = [ 'P2: ', num2str(round2(mean(sample_prop2_.*100),2e-1)), ' \pm ',  num2str(round2(std(sample_prop2_.*100),2e-1)) ,' %'];
        text(25,250,string,'Units','pixels')
        namePlot = strcat('Histogram_ErrorsEstimate_PP2_TripleExpo',timing_phase,'-',blastomere,'.fig');
        saveas(gcf,[save_stem namePlot]);
        
    elseif strcmp(original_best_model,'QuadroExpo')
        disp('plot not setup yet')
    end
end

end

